"""Artifact writers for the measurement pipeline.

Three outputs from a single fit + extract run:
  - .smis  (SeamlyMe / Seamly2D)
  - .csv   (code, seamly_name, value_cm)
  - .obj   (fitted SMPL-X body mesh — CLO3D-importable)

The SMIS writer mirrors scripts/export_seamlyme.py's render_smis but is
importable so the measure CLI can produce the .smis directly.
"""
from __future__ import annotations

import csv
import re
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

import numpy as np

from .seamly_catalog import CODE_TO_NAME


# ---------------------------------------------------------------------------
# CSV
# ---------------------------------------------------------------------------


def write_csv(
    catalog_values: dict[str, float],
    out_path: Path,
    include_judgment_blank: bool = False,
) -> None:
    """Emit `code, seamly_name, value_cm` rows for the catalog values.

    If include_judgment_blank is True, also write rows for codes we know
    about (CODE_TO_NAME) but couldn't extract — value_cm column empty.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["code", "seamly_name", "value_cm"])

        # Order: catalog code lexicographic.
        codes = sorted(set(catalog_values) | (set(CODE_TO_NAME)
                                              if include_judgment_blank else set()))
        for code in codes:
            name = CODE_TO_NAME.get(code, "")
            v = catalog_values.get(code)
            v_str = f"{float(v):.4f}" if v is not None else ""
            w.writerow([code, name, v_str])


# ---------------------------------------------------------------------------
# OBJ (fitted SMPL-X body mesh)
# ---------------------------------------------------------------------------


def write_obj(verts: np.ndarray, faces: np.ndarray, out_path: Path) -> None:
    """Wavefront OBJ with per-vertex normals + smoothing group enabled.

    `vn` + `s 1` make Blender / CLO3D shade the mesh smoothly on import
    (no manual Shade-Smooth step). SMPL-X has 10475 verts and 20908
    triangles, all manifold."""
    fn = np.cross(
        verts[faces[:, 1]] - verts[faces[:, 0]],
        verts[faces[:, 2]] - verts[faces[:, 0]],
    )
    fn /= np.linalg.norm(fn, axis=1, keepdims=True).clip(min=1e-12)
    vn = np.zeros_like(verts)
    for i in range(3):
        np.add.at(vn, faces[:, i], fn)
    vn /= np.linalg.norm(vn, axis=1, keepdims=True).clip(min=1e-12)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write("# body-scanner fitted SMPL-X mesh\n")
        for v in verts:
            f.write(f"v {v[0]:.6f} {v[1]:.6f} {v[2]:.6f}\n")
        for n in vn:
            f.write(f"vn {n[0]:.6f} {n[1]:.6f} {n[2]:.6f}\n")
        f.write("s 1\n")
        for tri in faces:
            a, b, c = tri[0]+1, tri[1]+1, tri[2]+1
            f.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")


# ---------------------------------------------------------------------------
# SMIS (SeamlyMe / Seamly2D XML)
# ---------------------------------------------------------------------------


def render_smis(
    seamly_values: dict[str, float],
    template_order: list[str],
) -> str:
    """Same XML shape as scripts/export_seamlyme.py::render_smis.
    seamly_values is keyed by SEAMLY NAME (e.g. 'bust_circ'), not code."""
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    head = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<smis>\n"
        f"    <!--Generated by body_scanner.measure.exports on {now}-->\n"
        "    <version>0.3.4</version>\n"
        "    <read-only>false</read-only>\n"
        "    <notes/>\n"
        "    <unit>cm</unit>\n"
        "    <pm_system>998</pm_system>\n"
        "    <personal>\n"
        "        <family-name/>\n"
        "        <given-name/>\n"
        "        <birth-date>1800-01-01</birth-date>\n"
        "        <gender>unknown</gender>\n"
        "        <email/>\n"
        "    </personal>\n"
        "    <body-measurements>\n"
    )
    rows: list[str] = []
    seen: set[str] = set()
    for name in template_order:
        val = seamly_values.get(name, 0)
        if isinstance(val, float) and val.is_integer():
            val = int(val)
        rows.append(f'        <m name="{xml_escape(name)}" value="{val}"/>')
        seen.add(name)
    for name in sorted(set(seamly_values) - seen):
        val = seamly_values[name]
        if isinstance(val, float) and val.is_integer():
            val = int(val)
        rows.append(f'        <m name="{xml_escape(name)}" value="{val}"/>')
    tail = "\n    </body-measurements>\n</smis>\n"
    return head + "\n".join(rows) + tail


def write_smis_from_catalog(
    catalog_values: dict[str, float],
    out_path: Path,
    template_path: Path | None = None,
) -> None:
    """Convert {code: value} -> {seamly_name: value} via CODE_TO_NAME, render
    XML, write to disk."""
    by_name: dict[str, float] = {}
    for code, val in catalog_values.items():
        name = CODE_TO_NAME.get(code)
        if name:
            by_name[name] = float(val)

    template_order: list[str] = []
    if template_path and Path(template_path).is_file():
        template_order = re.findall(
            r'<m\s+name="([^"]+)"', Path(template_path).read_text()
        )

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_smis(by_name, template_order))
