"""Generate `docs/catalog_coverage.md`: per-code table of every Seamly
catalog entry with recipe-class + last extracted value on Yaiza.

Run:
  python scripts/dump_recipe_table.py

Output: docs/catalog_coverage.md

Re-run after every recipe rewire so the doc tracks current state.
"""
from __future__ import annotations

import json
from pathlib import Path

from tailor_twin.measure.seamly_catalog import (
    CODE_TO_NAME,
    FORMULAS,
    JUDGMENT_OR_STANDARD,
    RECIPES,
)


REPO_ROOT = Path(__file__).resolve().parents[1]
YAIZA_JSON = REPO_ROOT / "data" / "results" / "yaiza_seamly_catalog.json"
OUT = REPO_ROOT / "docs" / "catalog_coverage.md"


def _recipe_class(code: str) -> str:
    if code in RECIPES:
        return type(RECIPES[code]).__name__
    if code in FORMULAS:
        return f"Formula({FORMULAS[code].expr!r})"
    return "—"


def _status(code: str, values: dict) -> str:
    if code in values:
        return "extracted"
    if code in JUDGMENT_OR_STANDARD:
        return f"skipped ({JUDGMENT_OR_STANDARD[code]})"
    if code in RECIPES or code in FORMULAS:
        return "skipped (runtime)"
    return "no recipe"


def main() -> int:
    values: dict[str, float] = {}
    if YAIZA_JSON.is_file():
        values = {k: float(v) for k, v in json.loads(
            YAIZA_JSON.read_text()).items()}
    all_codes = sorted(set(CODE_TO_NAME) | set(RECIPES) | set(FORMULAS)
                       | set(JUDGMENT_OR_STANDARD))

    lines: list[str] = []
    lines.append("# Seamly catalog coverage")
    lines.append("")
    lines.append(
        f"Auto-generated by `scripts/dump_recipe_table.py`. Values are the "
        f"latest Yaiza extraction (`{YAIZA_JSON.relative_to(REPO_ROOT)}`).")
    lines.append("")
    extracted = sum(1 for c in all_codes if c in values)
    skipped = sum(1 for c in all_codes
                  if c not in values and (c in RECIPES or c in FORMULAS))
    judgment = sum(1 for c in all_codes if c in JUDGMENT_OR_STANDARD)
    missing = sum(1 for c in all_codes
                  if c not in values and c not in RECIPES
                  and c not in FORMULAS and c not in JUDGMENT_OR_STANDARD)
    lines.append(
        f"**Summary:** {len(all_codes)} total — {extracted} extracted, "
        f"{skipped} skipped, {judgment} judgment/standard, {missing} "
        "without recipe.")
    lines.append("")
    lines.append("| Code | Seamly name | Recipe | Status | Value (cm) |")
    lines.append("|------|-------------|--------|--------|------------|")
    for code in all_codes:
        name = CODE_TO_NAME.get(code, "")
        recipe = _recipe_class(code)
        status = _status(code, values)
        val = f"{values[code]:.2f}" if code in values else ""
        lines.append(f"| {code} | {name} | {recipe} | {status} | {val} |")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(REPO_ROOT)} "
          f"({len(all_codes)} codes, {extracted} extracted)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
