#!/usr/bin/env python3
"""Emit a SeamlyMe .smis file from a values dict + merged.yaml mapping.

Workflow context:
  Phase 6-7 of the body-scanner pipeline produces a per-scan dictionary
  of measurement values keyed by the canonical names used in
  src/body_scanner/measure/definitions/merged.yaml (e.g.
  ``dpm_bodice_bust: 92.4``). SeamlyMe expects its own naming scheme
  (``bust_circ`` etc.) defined by the reference template at
  ~/seamly2d/templates/all_measurements_template.smis.

  This script bridges the two:
    - reads the seamly_name mapping from merged.yaml
    - reads a values JSON keyed by our canonical names
    - writes a .smis XML file using Seamly names

  Measurements without a Seamly equivalent (seamly_name: null) are
  skipped. Measurements present in the Seamly template but missing
  from our values dict are emitted with value="0" so SeamlyMe still
  loads the file cleanly.

Usage:
  scripts/export_seamlyme.py --values measurements.json --output out.smis
  scripts/export_seamlyme.py --output blank.smis        # all-zeros baseline

Values JSON shape:
  {
    "dpm_bodice_bust": 92.4,
    "aldrich_waist": 75.0,
    ...
  }

  Conflicts (two of our names map to the same Seamly name) resolve by
  preferring dpm_* over aldrich_*, then alphabetical order. The chosen
  value is logged to stderr.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape

import yaml

ROOT = Path(__file__).resolve().parent.parent
MERGED = ROOT / "src" / "body_scanner" / "measure" / "definitions" / "merged.yaml"
TEMPLATE = Path.home() / "seamly2d" / "templates" / "all_measurements_template.smis"
XSD = ROOT / "references" / "seamly" / "schema" / "individual_measurements_v0.3.4.xsd"


def load_mapping() -> dict[str, str]:
    """our canonical name -> seamly name (only mapped entries)."""
    doc = yaml.safe_load(MERGED.read_text())
    out: dict[str, str] = {}
    for m in doc["measurements"]:
        sn = m.get("seamly_name")
        if sn:
            out[m["name"]] = sn
    return out


def load_template_order() -> list[str]:
    """Seamly measurement names in their canonical template order."""
    if not TEMPLATE.is_file():
        return []
    import re
    return re.findall(r'<m\s+name="([^"]+)"', TEMPLATE.read_text())


def resolve_seamly_values(
    values: dict[str, float], mapping: dict[str, str]
) -> dict[str, float]:
    """our-name -> value  +  our-name -> seamly-name  ->  seamly-name -> value.

    On conflict, prefer dpm_* over aldrich_*, then alphabetical.
    """
    candidates: dict[str, list[tuple[str, float]]] = {}
    for our_name, val in values.items():
        seamly = mapping.get(our_name)
        if not seamly:
            print(f"skip: '{our_name}' has no seamly_name (or no mapping)", file=sys.stderr)
            continue
        candidates.setdefault(seamly, []).append((our_name, val))

    def rank(our_name: str) -> tuple[int, str]:
        prefix_order = {"dpm_": 0, "aldrich_": 1}
        for p, r in prefix_order.items():
            if our_name.startswith(p):
                return (r, our_name)
        return (2, our_name)

    resolved: dict[str, float] = {}
    for seamly, pairs in candidates.items():
        if len(pairs) > 1:
            pairs.sort(key=lambda p: rank(p[0]))
            chosen = pairs[0]
            others = [p[0] for p in pairs[1:]]
            print(
                f"conflict on '{seamly}': using '{chosen[0]}'={chosen[1]} "
                f"over {others}",
                file=sys.stderr,
            )
        resolved[seamly] = pairs[0][1]
    return resolved


def validate_xsd(smis_path: Path, xsd_path: Path = XSD) -> bool:
    """Validate .smis against XSD using xmllint. Returns True if valid."""
    if not xsd_path.is_file():
        print(f"warn: XSD not found at {xsd_path}; skipping validation", file=sys.stderr)
        return True
    result = subprocess.run(
        ["xmllint", "--noout", "--schema", str(xsd_path), str(smis_path)],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        print(f"xsd: {smis_path.name} validates OK", file=sys.stderr)
        return True
    print(f"xsd: VALIDATION FAILED for {smis_path.name}", file=sys.stderr)
    print(result.stderr, file=sys.stderr)
    return False


def render_smis(seamly_values: dict[str, float], template_order: list[str]) -> str:
    """Render the .smis XML. Uses the template's measurement order if available."""
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    head = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<smis>\n"
        f"    <!--Generated by scripts/export_seamlyme.py on {now}-->\n"
        "    <version>0.3.4</version>\n"
        "    <read-only>false</read-only>\n"
        "    <notes/>\n"
        "    <unit>cm</unit>\n"
        "    <pm_system>998</pm_system>\n"
        "    <personal>\n"
        "        <family-name/>\n"
        "        <given-name/>\n"
        "        <birth-date>1800-01-01</birth-date>\n"
        "        <gender>unknown</gender>\n"
        "        <email/>\n"
        "    </personal>\n"
        "    <body-measurements>\n"
    )
    rows: list[str] = []
    seen: set[str] = set()
    for name in template_order:
        val = seamly_values.get(name, 0)
        if isinstance(val, float) and val.is_integer():
            val = int(val)
        rows.append(f'        <m name="{xml_escape(name)}" value="{val}"/>')
        seen.add(name)
    # Append any seamly names we have values for that aren't in the template.
    extras = sorted(set(seamly_values) - seen)
    for name in extras:
        val = seamly_values[name]
        if isinstance(val, float) and val.is_integer():
            val = int(val)
        rows.append(f'        <m name="{xml_escape(name)}" value="{val}"/>')
        print(f"warn: '{name}' not in template; appended at end", file=sys.stderr)
    tail = "\n    </body-measurements>\n</smis>\n"
    return head + "\n".join(rows) + tail


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--values", type=Path, help="JSON dict of {our_name: value_cm}")
    p.add_argument("--output", type=Path, required=True, help=".smis output path")
    p.add_argument(
        "--template",
        type=Path,
        default=TEMPLATE,
        help=f"Reference .smis whose order is preserved (default: {TEMPLATE})",
    )
    p.add_argument(
        "--no-validate",
        action="store_true",
        help="Skip XSD validation of the output file",
    )
    args = p.parse_args()

    mapping = load_mapping()
    print(f"mapping: {len(mapping)} seamly names from merged.yaml", file=sys.stderr)

    if args.values:
        raw = json.loads(args.values.read_text())
        print(f"values: {len(raw)} entries from {args.values}", file=sys.stderr)
    else:
        raw = {}
        print("no --values: emitting all-zeros baseline", file=sys.stderr)

    seamly_values = resolve_seamly_values(raw, mapping)
    template_order: list[str] = []
    if args.template.is_file():
        import re
        template_order = re.findall(r'<m\s+name="([^"]+)"', args.template.read_text())
        print(
            f"template order: {len(template_order)} slots from {args.template}",
            file=sys.stderr,
        )
    else:
        print(
            f"warn: template {args.template} not found; emitting only mapped values",
            file=sys.stderr,
        )
        template_order = sorted(seamly_values)

    xml = render_smis(seamly_values, template_order)
    args.output.write_text(xml)
    print(f"wrote {args.output}", file=sys.stderr)

    if not args.no_validate:
        if not validate_xsd(args.output):
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
